EMOJI_TO_CLASS = {
    "🧑": "Person",
    "👟": "Sneakers",
    "🪑": "Chair",
    "👞": "Other Shoes",
    "🎩": "Hat",
    "🚗": "Car",
    "💡": "Lamp",
    "👓": "Glasses",
    "🍾": "Bottle",
    "🛋️": "Desk",
    "☕": "Cup",
    "🚦": "Street Lights",
    "🗄️": "Cabinet/shelf",
    "👜": "Handbag/Satchel",
    "📿": "Bracelet",
    "🍽️": "Plate",
    "🖼️": "Picture/Frame",
    "⛑️": "Helmet",
    "📚": "Book",
    "🧤": "Gloves",
    "📦": "Storage box",
    "⛵": "Boat",
    "👞": "Leather Shoes",
    "🌸": "Flower",
    "🪑": "Bench",
    "🪴": "Potted Plant",
    "🥣": "Bowl/Basin",
    "🚩": "Flag",
    "🛏️": "Pillow",
    "🥾": "Boots",
    "🏺": "Vase",
    "🎤": "Microphone",
    "📿": "Necklace",
    "💍": "Ring",
    "🚙": "SUV",
    "🍷": "Wine Glass",
    "🧣": "Belt",
    "🖥️": "Monitor/TV",
    "🎒": "Backpack",
    "☂️": "Umbrella",
    "🚥": "Traffic Light",
    "🔊": "Speaker",
    "⌚": "Watch",
    "👔": "Tie",
    "🗑️": "Trash bin Can",
    "🩴": "Slippers",
    "🚲": "Bicycle",
    "🪑": "Stool",
    "🪣": "Barrel/bucket",
    "🚐": "Van",
    "🛋️": "Couch",
    "🩴": "Sandals",
    "🧺": "Basket",
    "🥁": "Drum",
    "✏️": "Pen/Pencil",
    "🚌": "Bus",
    "🐦": "Wild Bird",
    "👠": "High Heels",
    "🏍️": "Motorcycle",
    "🎸": "Guitar",
    "🧶": "Carpet",
    "📱": "Cell Phone",
    "🍞": "Bread",
    "📷": "Camera",
    "🥫": "Canned",
    "🚛": "Truck",
    "🚧": "Traffic cone",
    "🥁": "Cymbal",
    "🛟": "Lifesaver",
    "🧻": "Towel",
    "🧸": "Stuffed Toy",
    "🕯️": "Candle",
    "⛵": "Sailboat",
    "💻": "Laptop",
    "⛱️": "Awning",
    "🛏️": "Bed",
    "🚰": "Faucet",
    "⛺": "Tent",
    "🐴": "Horse",
    "🪞": "Mirror",
    "🔌": "Power outlet",
    "🚿": "Sink",
    "🍎": "Apple",
    "❄️": "Air Conditioner",
    "🔪": "Knife",
    "🏒": "Hockey Stick",
    "🛶": "Paddle",
    "🛻": "Pickup Truck",
    "🍴": "Fork",
    "🚸": "Traffic Sign",
    "🎈": "Balloon",
    "📷": "Tripod",
    "🐶": "Dog",
    "🥄": "Spoon",
    "⏰": "Clock",
    "🫖": "Pot",
    "🐄": "Cow",
    "🍰": "Cake",
    "🍽️": "Dining Table",
    "🐑": "Sheep",
    "🪝": "Hanger",
    "⚫": "Blackboard/Whiteboard",
    "🧻": "Napkin",
    "🐟": "Other Fish",
    "🍊": "Orange/Tangerine",
    "🧴": "Toiletry",
    "⌨️": "Keyboard",
    "🍅": "Tomato",
    "🏮": "Lantern",
    "🚜": "Machinery Vehicle",
    "🌀": "Fan",
    "🥦": "Green Vegetables",
    "🍌": "Banana",
    "🧤": "Baseball Glove",
    "✈️": "Airplane",
    "🖱️": "Mouse",
    "🚆": "Train",
    "🎃": "Pumpkin",
    "⚽": "Soccer",
    "🎿": "Skiboard",
    "🧳": "Luggage",
    "🛏️": "Nightstand",
    "🍵": "Tea pot",
    "☎️": "Telephone",
    "🛒": "Trolley",
    "🎧": "Head Phone",
    "🏎️": "Sports Car",
    "🛑": "Stop Sign",
    "🍮": "Dessert",
    "🛴": "Scooter",
    "🚼": "Stroller",
    "🏗️": "Crane",
    "📺": "Remote",
    "🧊": "Refrigerator",
    "🔥": "Oven",
    "🍋": "Lemon",
    "🦆": "Duck",
    "🏏": "Baseball Bat",
    "📸": "Surveillance Camera",
    "🐱": "Cat",
    "🍶": "Jug",
    "🥦": "Broccoli",
    "🎹": "Piano",
    "🍕": "Pizza",
    "🐘": "Elephant",
    "🛹": "Skateboard",
    "🏄": "Surfboard",
    "🔫": "Gun",
    "⛸️": "Skating and Skiing shoes",
    "🍳": "Gas stove",
    "🍩": "Donut",
    "👔": "Bow Tie",
    "🥕": "Carrot",
    "🚽": "Toilet",
    "🪁": "Kite",
    "🍓": "Strawberry",
    "⚽": "Other Balls",
    "🛠️": "Shovel",
    "🌶️": "Pepper",
    "💻": "Computer Box",
    "🧻": "Toilet Paper",
    "🧼": "Cleaning Products",
    "🥢": "Chopsticks",
    "🍲": "Microwave",
    "🕊️": "Pigeon",
    "⚾": "Baseball",
    "🔪": "Cutting/chopping Board",
    "🛋️": "Coffee Table",
    "🛋️": "Side Table",
    "✂️": "Scissors",
    "🖊️": "Marker",
    "🥧": "Pie",
    "🪜": "Ladder",
    "🏂": "Snowboard",
    "🍪": "Cookies",
    "♨️": "Radiator",
    "🚒": "Fire Hydrant",
    "🏀": "Basketball",
    "🦓": "Zebra",
    "🍇": "Grape",
    "🦒": "Giraffe",
    "🥔": "Potato",
    "🌭": "Sausage",
    "🚲": "Tricycle",
    "🎻": "Violin",
    "🥚": "Egg",
    "🧯": "Fire Extinguisher",
    "🍬": "Candy",
    "🚒": "Fire Truck",
    "🎱": "Billiards",
    "🔌": "Converter",
    "🛁": "Bathtub",
    "♿": "Wheelchair",
    "🏌️": "Golf Club",
    "💼": "Briefcase",
    "🥒": "Cucumber",
    "🚬": "Cigar/Cigarette",
    "🖌️": "Paint Brush",
    "🍐": "Pear",
    "🚚": "Heavy Truck",
    "🍔": "Hamburger",
    "🍳": "Extractor",
    "🔌": "Extension Cord",
    "🫖": "Tong",
    "🎾": "Tennis Racket",
    "📁": "Folder",
    "🏈": "American Football",
    "🎧": "earphone",
    "😷": "Mask",
    "☕": "Kettle",
    "🎾": "Tennis",
    "🚢": "Ship",
    "🛝": "Swing",
    "☕": "Coffee Machine",
    "🛝": "Slide",
    "🛞": "Carriage",
    "🧅": "Onion",
    "🥬": "Green beans",
    "📽️": "Projector",
    "🥏": "Frisbee",
    "🧺": "Washing Machine/Drying Machine",
    "🐔": "Chicken",
    "🖨️": "Printer",
    "🍉": "Watermelon",
    "🎷": "Saxophone",
    "🧻": "Tissue",
    "🪥": "Toothbrush",
    "🍦": "Ice cream",
    "🎈": "Hot-air balloon",
    "🎻": "Cello",
    "🍟": "French Fries",
    "⚖️": "Scale",
    "🏆": "Trophy",
    "🥬": "Cabbage",
    "🌭": "Hot dog",
    "🧊": "Blender",
    "🍑": "Peach",
    "🍚": "Rice",
    "👛": "Wallet/Purse",
    "🏐": "Volleyball",
    "🦌": "Deer",
    "🦢": "Goose",
    "📼": "Tape",
    "📱": "Tablet",
    "化妆品": "Cosmetics",
    "🎺": "Trumpet",
    "🍍": "Pineapple",
    "🏌️‍♂️": "Golf Ball",
    "🚑": "Ambulance",
    "🅿️": "Parking meter",
    "🥭": "Mango",
    "🗝️": "Key",
    "🏃‍♂️": "Hurdle",
    "🎣": "Fishing Rod",
    "🥇": "Medal",
    "🎶": "Flute",
    "🖌️": "Brush",
    "🐧": "Penguin",
    "📣": "Megaphone",
    "🌽": "Corn",
    "🥗": "Lettuce",
    "🧄": "Garlic",
    "🦢": "Swan",
    "🚁": "Helicopter",
    "🧅": "Green Onion",
    "🥪": "Sandwich",
    "🥜": "Nuts",
    "🚦": "Speed Limit Sign",
    "🍳": "Induction Cooker",
    "🧹": "Broom",
    "🎺": "Trombone",
    "🍑": "Plum",
    "🚲": "Rickshaw",
    "🐠": "Goldfish",
    "🥝": "Kiwi fruit",
    "📡": "Router/modem",
    "🃏": "Poker Card",
    "🍞": "Toaster",
    "🦐": "Shrimp",
    "🍣": "Sushi",
    "🧀": "Cheese",
    "📄": "Notepaper",
    "🍒": "Cherry",
    "🔧": "Pliers",
    "💿": "CD",
    "🍝": "Pasta",
    "🔨": "Hammer",
    "🎱": "Cue",
    "🥑": "Avocado",
    "🍈": "Hami melon",
    "🥛": "Flask",
    "🍄": "Mushroom",
    "🔩": "Screwdriver",
    "🧼": "Soap",
    "🎶": "Recorder",
    "🐻": "Bear",
    "🍆": "Eggplant",
    "🧽": "Board Eraser",
    "🥥": "Coconut",
    "📏": "Tape Measure/Ruler",
    "🐖": "Pig",
    "🚿": "Showerhead",
    "🌍": "Globe",
    "🍟": "Chips",
    "🥩": "Steak",
    "🚸": "Crosswalk Sign",
    "📎": "Stapler",
    "🐫": "Camel",
    "🏎️": "Formula 1",
    "🥭": "Pomegranate",
    "🍽️": "Dishwasher",
    "🦀": "Crab",
    "🛹": "Hoverboard",
    "🍡": "Meatball",
    "🍚": "Rice Cooker",
    "🎺": "Tuba",
    "🧮": "Calculator",
    "🥭": "Papaya",
    "🦌": "Antelope",
    "🦜": "Parrot",
    "🦭": "Seal",
    "🦋": "Butterfly",
    "🏋️": "Dumbbell",
    "🫏": "Donkey",
    "🦁": "Lion",
    "🚽": "Urinal",
    "🐬": "Dolphin",
    "🛠️": "Electric Drill",
    "💇": "Hair Dryer",
    "🥧": "Egg tart",
    "🪼": "Jellyfish",
    "🏃‍♂️": "Treadmill",
    "🔥": "Lighter",
    "🍊": "Grapefruit",
    "🎲": "Game board",
    "🧹": "Mop",
    "🫑": "Radish",
    "🥟": "Baozi",
    "🎯": "Target",
    "🇫🇷": "French",
    "🥟": "Spring Rolls",
    "🐒": "Monkey",
    "🐇": "Rabbit",
    "✏️": "Pencil Case",
    "🐂": "Yak",
    "🥬": "Red Cabbage",
    "🔭": "Binoculars",
    "🥬": "Asparagus",
    "🏋️‍♂️": "Barbell",
    "🦪": "Scallop",
    "🍜": "Noddles",
    "💇": "Comb",
    "🥟": "Dumpling",
    "🦪": "Oyster",
    "🏓": "Table Tennis paddle",
    "💄": "Cosmetics Brush/Eyeliner Pencil",
    "🪚": "Chainsaw",
    "🩹": "Eraser",
    "🦞": "Lobster",
    "🍈": "Durian",
    "🥬": "Okra",
    "💄": "Lipstick",
    "🪞": "Cosmetics Mirror",
    "⛸️": "Curling",
    "🏓": "Table Tennis"
}