
EMOJI_TO_CLASS = {
    "🧍🏻‍♂️": "Person",
    "👟": "Sneakers",
    "🪑": "Chair",
    "👞": "Other Shoes",
    "🧢": "Hat",
    "💡": "Lamp",
    "👓": "Glasses",
    "🍾": "Bottle",
    "☕️": "Cup",
    "🗄️": "Cabinet/shelf",
    "👜": "Handbag/Satchel",
    "📿": "Bracelet",
    "🍽️": "Plate",
    "🖼️": "Picture/Frame",
    "📚": "Book",
    "🧤": "Gloves",
    "📦": "Storage box",
    "👞": "Leather Shoes",
    "🌻": "Flower",
    "🪴": "Potted Plant",
    "🥣": "Bowl/Basin",
    "🛌": "Pillow",
    "🏺": "Vase",
    "📿": "Necklace",
    "💍": "Ring",
    "🍷": "Wine Glass",
    "📺": "Monitor/TV",
    "🎒": "Backpack",
    "☂️": "Umbrella",
    "🔊": "Speaker",
    "⌚": "Watch",
    "👔": "Tie",
    "🗑️": "Trash bin Can",
    "🩴": "Slippers",
    "🪑": "Stool",
    "🪣": "Barrel/bucket",
    "🛋️": "Couch",
    "🩴": "Sandals",
    "🧺": "Basket",
    "🛢️": "Drum",
    "✏️": "Pen/Pencil",
    "👠": "High Heels",
    "🎸": "Guitar",
    "📱": "Cell Phone",
    "🍞": "Bread",
    "📷": "Camera",
    "🥫": "Canned",
    "🧻": "Towel",
    "🧸": "Stuffed Toy",
    "🕯️": "Candle",
    "💻": "Laptop",
    "🛏️": "Bed",
    "🚰": "Faucet",
    "🪞": "Mirror",
    "🔌": "Power outlet",
    "🚿": "Sink",
    "🍎": "Apple",
    "🔪": "Knife",
    "🍴": "Fork",
    "🎈": "Balloon",
    "🐶": "Dog",
    "🥄": "Spoon",
    "🕰️": "Clock",
    "🫖": "Pot",
    "🍰": "Cake",
    "🧻": "Napkin",
    "🍊": "Orange/Tangerine",
    "🧴": "Toiletry",
    "⌨️": "Keyboard",
    "🍅": "Tomato",
    "🥦": "Green Vegetables",
    "🍌": "Banana",
    "🎃": "Pumpkin",
    "🧳": "Luggage",
    "🫖": "Tea pot",
    "☎️": "Telephone",
    "🛒": "Trolley",
    "🎧": "Head Phone",
    "🍮": "Dessert",
    "🍋": "Lemon",
    "🐱": "Cat",
    "🍶": "Jug",
    "🥦": "Broccoli",
    "🎹": "Piano",
    "🍕": "Pizza",
    "🛹": "Skateboard",
    "🍩": "Donut",
    "🥕": "Carrot",
    "🚽": "Toilet",
    "🍓": "Strawberry",
    "⚽": "Other Balls",
    "🪏": "Shovel",
    "🌶️": "Pepper",
    "🧻": "Toilet Paper",
    "🧼": "Cleaning Products",
    "🥢": "Chopsticks",
    "⚾": "Baseball",
    "🔪": "Cutting/chopping Board",
    "✂️": "Scissors",
    "🖊️": "Marker",
    "🥧": "Pie",
    "🪜": "Ladder",
    "🍪": "Cookies",
    "🏀": "Basketball",
    "🍇": "Grape",
    "🥔": "Potato",
    "🌭": "Sausage",
    "🎻": "Violin",
    "🥚": "Egg",
    "🧯": "Fire Extinguisher",
    "🍬": "Candy",
    "🛁": "Bathtub",
    "💼": "Briefcase",
    "🥒": "Cucumber",
    "🚬": "Cigar/Cigarette",
    "🧑🏻‍🎨": "Paint Brush",
    "🍐": "Pear",
    "🍔": "Hamburger",
    "🔌": "Extension Cord",
    "🎧": "earphone",
    "🫖": "Kettle",
    "🎾": "Tennis",
    "☕️": "Coffee Machine",
    "🛝": "Slide",
    "🧅": "Onion",
    "🫛": "Green beans",
    "🧺": "Washing Machine/Drying Machine",
    "🖨️": "Printer",
    "🍉": "Watermelon",
    "🎷": "Saxophone",
    "🧻": "Tissue",
    "🪥": "Toothbrush",
    "🍦": "Ice cream",
    "🎻": "Cello",
    "🍟": "French Fries",
    "⚖️": "Scale",
    "🏆": "Trophy",
    "🥬": "Cabbage",
    "🌭": "Hot dog",
    "🍑": "Peach",
    "🍚": "Rice",
    "👛": "Wallet/Purse",
    "🎺": "Trumpet",
    "🍍": "Pineapple",
    "🥭": "Mango",
    "🗝️": "Key",
    "🎣": "Fishing Rod",
    "🥇": "Medal",
    "📣": "Megaphone",
    "🌽": "Corn",
    "🥗": "Lettuce",
    "🧄": "Garlic",
    "🦢": "Swan",
    "🧅": "Green Onion",
    "🥪": "Sandwich",
    "🥜": "Nuts",
    "🍳": "Induction Cooker",
    "🧹": "Broom",
    "🐠": "Goldfish",
    "🥝": "Kiwi fruit",
    "🃏": "Poker Card",
    "🦐": "Shrimp",
    "🍣": "Sushi",
    "🧀": "Cheese",
    "📄": "Notepaper",
    "🍒": "Cherry",
    "💿": "CD",
    "🍝": "Pasta",
    "🔨": "Hammer",
    "🎱": "Cue",
    "🥑": "Avocado",
    "🍄": "Mushroom",
    "🪛": "Screwdriver",
    "🧼": "Soap",
    "🍆": "Eggplant",
    "🧽": "Board Eraser",
    "🥥": "Coconut",
    "📏": "Tape Measure/Ruler",
    "🚿": "Showerhead",
    "🌍": "Globe",
    "🍟": "Chips",
    "🥩": "Steak",
    "🍽️": "Dishwasher",
    "🔥": "Lighter",
    "🍊": "Grapefruit",
    "🎲": "Game board",
    "🐇": "Rabbit",
    "✏️": "Pencil Case",
    "🪮": "Comb",
    "🥟": "Dumpling",
    "🦪": "Oyster",
    "🏓": "Table Tennis paddle",
    "💄": "Cosmetics Brush/Eyeliner Pencil",
    "🩹": "Eraser",
}




# EMOJI_TO_CLASS = {
#     "🧍🏻‍♂️": "Person",
#     "👟": "Sneakers",
#     "🪑": "Chair",
#     "👞": "Other Shoes",
#     "🧢": "Hat",
#     #"🚗": "Car",
#     "💡": "Lamp",
#     "👓": "Glasses",
#     "🍾": "Bottle",
#     "☕️": "Cup",
#     #"🚦": "Street Lights",
#     "🗄️": "Cabinet/shelf",
#     "👜": "Handbag/Satchel",
#     "📿": "Bracelet",
#     "🍽️": "Plate",
#     "🖼️": "Picture/Frame",
#     "⛑️": "Helmet",
#     "📚": "Book",
#     "🧤": "Gloves",
#     "📦": "Storage box",
#     #"⛵": "Boat",
#     "👞": "Leather Shoes",
#     "🌻": "Flower",
#     "🪴": "Potted Plant",
#     "🥣": "Bowl/Basin",
#     "🚩": "Flag",
#     "🛌": "Pillow",
#     "🥾": "Boots",
#     "🏺": "Vase",
#     #"🎤": "Microphone",
#     "📿": "Necklace",
#     "💍": "Ring",
#     "🍷": "Wine Glass",
#     "📺": "Monitor/TV",
#     "🎒": "Backpack",
#     "☂️": "Umbrella",
#     #"🚥": "Traffic Light",
#     "🔊": "Speaker",
#     "⌚": "Watch",
#     "👔": "Tie",
#     "🗑️": "Trash bin Can",
#     "🩴": "Slippers",
#     #"🚲": "Bicycle",
#     "🪑": "Stool",
#     "🪣": "Barrel/bucket",
#     "🚐": "Van",
#     "🛋️": "Couch",
#     "🩴": "Sandals",
#     "🧺": "Basket",
#     "🛢️": "Drum",
#     "✏️": "Pen/Pencil",
#     #"🚌": "Bus",
#     #"🐦‍⬛": "Wild Bird",
#     "👠": "High Heels",
#     #"🏍️": "Motorcycle",
#     "🎸": "Guitar",
#     "📱": "Cell Phone",
#     "🍞": "Bread",
#     "📷": "Camera",
#     "🥫": "Canned",
#     #"🚛": "Truck",
#     #"🛟": "Lifesaver",
#     "🧻": "Towel",
#     "🧸": "Stuffed Toy",
#     "🕯️": "Candle",
#     #"⛵": "Sailboat",
#     "💻": "Laptop",
#     "🛏️": "Bed",
#     "🚰": "Faucet",
#     #"⛺": "Tent",
#     #"🐴": "Horse",
#     "🪞": "Mirror",
#     "🔌": "Power outlet",
#     "🚿": "Sink",
#     "🍎": "Apple",
#     "🔪": "Knife",
#     #"🏒": "Hockey Stick",
#     #"🛻": "Pickup Truck",
#     "🍴": "Fork",
#     #"🚸": "Traffic Sign",
#     "🎈": "Balloon",
#     #"📷": "Tripod",
#     "🐶": "Dog",
#     "🥄": "Spoon",
#     "🕰️": "Clock",
#     "🫖": "Pot",
#     "🐄": "Cow",
#     "🍰": "Cake",
#     "🐑": "Sheep",
#     "🧻": "Napkin",
#     "🐟": "Other Fish",
#     "🍊": "Orange/Tangerine",
#     "🧴": "Toiletry",
#     "⌨️": "Keyboard",
#     "🍅": "Tomato",
#     "🏮": "Lantern",
#     #"🚜": "Machinery Vehicle",
#     "🥦": "Green Vegetables",
#     "🍌": "Banana",
#     #"✈️": "Airplane",
#     #"🚆": "Train",
#     "🎃": "Pumpkin",
#     "⚽": "Soccer",
#     #"🎿": "Skiboard",
#     "🧳": "Luggage",
#     "🫖": "Tea pot",
#     "☎️": "Telephone",
#     "🛒": "Trolley",
#     "🎧": "Head Phone",
#    # "🏎️": "Sports Car",
#    # "🛑": "Stop Sign",
#     "🍮": "Dessert",
#     #"🛴": "Scooter",
#     #"🏗️": "Crane",
#     "🍋": "Lemon",
#     #"🦆": "Duck",
#     "🐱": "Cat",
#     "🍶": "Jug",
#     "🥦": "Broccoli",
#     "🎹": "Piano",
#     "🍕": "Pizza",
#     #"🐘": "Elephant",
#     "🛹": "Skateboard",
#     #"🏄": "Surfboard",
#     #"⛸️": "Skating and Skiing shoes",
#     "🍩": "Donut",
#     "🥕": "Carrot",
#     "🚽": "Toilet",
#     #"🪁": "Kite",
#     "🍓": "Strawberry",
#     "⚽": "Other Balls",
#     "🪏": "Shovel",
#     "🌶️": "Pepper",
#     "🧻": "Toilet Paper",
#     "🧼": "Cleaning Products",
#     "🥢": "Chopsticks",
#     #"🕊️": "Pigeon",
#     "⚾": "Baseball",
#     "🔪": "Cutting/chopping Board",
#     "✂️": "Scissors",
#     "🖊️": "Marker",
#     "🥧": "Pie",
#     "🪜": "Ladder",
#     #"🏂": "Snowboard",
#     "🍪": "Cookies",
#     "🏀": "Basketball",
#     #"🦓": "Zebra",
#     "🍇": "Grape",
#     #"🦒": "Giraffe",
#     "🥔": "Potato",
#     "🌭": "Sausage",
#     #"🚲": "Tricycle",
#     "🎻": "Violin",
#     "🥚": "Egg",
#     "🧯": "Fire Extinguisher",
#     "🍬": "Candy",
#     #"🚒": "Fire Truck",
#     #"🎱": "Billiards",
#     "🛁": "Bathtub",
#     #"🏌️": "Golf Club",
#     "💼": "Briefcase",
#     "🥒": "Cucumber",
#     "🚬": "Cigar/Cigarette",
#     "🧑🏻‍🎨": "Paint Brush",
#     "🍐": "Pear",
#     #"🚚": "Heavy Truck",
#     "🍔": "Hamburger",
#     "🔌": "Extension Cord",
#     #"🏈": "American Football",
#     "🎧": "earphone",
#     "🫖": "Kettle",
#     "🎾": "Tennis",
#     #"🚢": "Ship",
#     "☕️": "Coffee Machine",
#     "🛝": "Slide",
#     "🧅": "Onion",
#     "🫛": "Green beans",
#     #"📽️": "Projector",
#     #"🥏": "Frisbee",
#     "🧺": "Washing Machine/Drying Machine",
#     #"🐔": "Chicken",
#     "🖨️": "Printer",
#     "🍉": "Watermelon",
#     "🎷": "Saxophone",
#     "🧻": "Tissue",
#     "🪥": "Toothbrush",
#     "🍦": "Ice cream",
#     "🎻": "Cello",
#     "🍟": "French Fries",
#     "⚖️": "Scale",
#     "🏆": "Trophy",
#     "🥬": "Cabbage",
#     "🌭": "Hot dog",
#     "🍑": "Peach",
#     "🍚": "Rice",
#     "👛": "Wallet/Purse",
#     #"🏐": "Volleyball",
#     #"🦌": "Deer",
#     #"🦢": "Goose",
#     "🎺": "Trumpet",
#     "🍍": "Pineapple",
#     #"🏌️‍♂️": "Golf Ball",
#     #"🚑": "Ambulance",
#     "🥭": "Mango",
#     "🗝️": "Key",
#     "🎣": "Fishing Rod",
#     "🥇": "Medal",
#     #"🐧": "Penguin",
#     "📣": "Megaphone",
#     "🌽": "Corn",
#     "🥗": "Lettuce",
#     "🧄": "Garlic",
#     "🦢": "Swan",
#     #"🚁": "Helicopter",
#     "🧅": "Green Onion",
#     "🥪": "Sandwich",
#     "🥜": "Nuts",
#     "🍳": "Induction Cooker",
#     "🧹": "Broom",
#     #"🎺": "Trombone",
#     "🐠": "Goldfish",
#     "🥝": "Kiwi fruit",
#     "🃏": "Poker Card",
#     "🦐": "Shrimp",
#     "🍣": "Sushi",
#     "🧀": "Cheese",
#     "📄": "Notepaper",
#     "🍒": "Cherry",
#     "💿": "CD",
#     "🍝": "Pasta",
#     "🔨": "Hammer",
#     "🎱": "Cue",
#     "🥑": "Avocado",
#     "🍄": "Mushroom",
#     "🪛": "Screwdriver",
#     "🧼": "Soap",
#     #"🐻": "Bear",
#     "🍆": "Eggplant",
#     "🧽": "Board Eraser",
#     "🥥": "Coconut",
#     "📏": "Tape Measure/Ruler",
#     #"🐖": "Pig",
#     "🚿": "Showerhead",
#     "🌍": "Globe",
#     "🍟": "Chips",
#     "🥩": "Steak",
#     #"🚸": "Crosswalk Sign",
#     "🐫": "Camel",
#     #"🏎️": "Formula 1",
#     "🍽️": "Dishwasher",
#     #"🦀": "Crab",
#     "🐬": "Dolphin",
#     "🥧": "Egg tart",
#     "🔥": "Lighter",
#     "🍊": "Grapefruit",
#     "🎲": "Game board",
#     #"🐒": "Monkey",
#     "🐇": "Rabbit",
#     "✏️": "Pencil Case",
#     "🪮": "Comb",
#     "🥟": "Dumpling",
#     "🦪": "Oyster",
#     "🏓": "Table Tennis paddle",
#     "💄": "Cosmetics Brush/Eyeliner Pencil",
#     "🩹": "Eraser",
#     }