# Base image
FROM opencv/opencv:4.8.1-python3.10

# Environment
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Copy only requirements first (for caching)
COPY requirements.txt .
COPY yolo11n_object365.pt .

# Install dependencies (this layer will be cached if requirements.txt hasn't changed)
RUN apt-get update && apt-get install -y libgl1 libglib2.0-0 \
    && pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application
COPY . .

# Expose port
EXPOSE 80

# Start the app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
